// export const FEELINGS = [
//   {
//     HAPPY: [
//       {
//         joyful: ['liberated', 'ecstatic'],
//         interested: ['inquisitive', 'curious'],
//         proud: ['confident', 'valued'],
//         accepted: ['accepted', 'approved'],
//         powerful: ['empowered', 'courageous'],
//         intimate: ['playful', 'sensitive'],
//         appreciative: ['thankful', 'loving'],
//         optimistic: ['inspired', 'hopeful'],
//         playful: ['animated', 'flirty'],
//       },
//     ],
//     SURPRISED: {
//       startled: ['dismayed', 'shocked'],
//       confused: ['disoriented', 'uncertain'],
//       amazed: ['astonished', 'awestruck'],
//       excited: ['eager', 'energetic'],
//     },
//     CALM: {
//       settled: ['grounded', 'steady'],
//       safe: ['protected', 'secure'],
//       present: ['mindful', 'attentive'],
//       balanced: ['centered', 'composed'],
//       rested: ['restored', 'refreshed'],
//     },
//     SAD: {
//       guilty: ['ashamed', 'remorseful'],
//       abandoned: ['ignored', 'victimized'],
//       despair: ['powerless', 'vulnerable'],
//       depressed: ['numb', 'empty'],
//       lonely: ['isolated', 'unseen'],
//       bored: ['listless', 'unstimulated'],
//     },
//     DISGUSTED: {
//       disapproval: ['judgmental', 'contemptuous'],
//       disappointment: ['repelled', 'revolted'],
//       disturbed: ['uneasy', 'unsettled'],
//       avoidant: ['averse', 'hesitant'],
//     },
//     ANGRY: {
//       hurt: ['devastated', 'embarrassed'],
//       threatened: ['jealous', 'guarded'],
//       hateful: ['violated', 'resentful'],
//       mad: ['enraged', 'furious'],
//       aggressive: ['provoked', 'hostile'],
//       frustrated: ['irritated', 'infuriated'],
//       distant: ['suspicious', 'withdrawn'],
//       critical: ['sarcastic', 'dismissive'],
//     },
//     FEAR: {
//       anxious: ['overwhelmed', 'worried'],
//       scared: ['frightened', 'terrified'],
//       insecure: ['inferior', 'inadequate'],
//       submissive: ['insignificant', 'devalued'],
//       rejected: ['excluded', 'unwanted'],
//       humiliated: ['ridiculed', 'disrespected'],
//     },
//   },
// ];

import { GROUP_COLORS } from '../../../styles/feelings-colors';
import type { FeelingsContent } from '../types';

export const FEELINGS_CONTENT: FeelingsContent = {
  version: 1,

  groups: [
    {
      id: 'happy',
      label: 'Happy',
      description: 'Pleasant, energized, or connected states.',
      color: GROUP_COLORS.happy,
    },
    {
      id: 'surprised',
      label: 'Surprised',
      description: 'Responses to the unexpected—positive, neutral, or negative.',
      color: GROUP_COLORS.surprised,
    },
    {
      id: 'calm',
      label: 'Calm',
      description: 'Settled, steady states with low threat and ease.',
      color: GROUP_COLORS.calm,
    },
    {
      id: 'sad',
      label: 'Sad',
      description: 'Loss, heaviness, or low-energy states.',
      color: GROUP_COLORS.sad,
    },
    {
      id: 'disgusted',
      label: 'Disgusted',
      description: 'Aversion, rejection, or emotional recoil.',
      color: GROUP_COLORS.disgusted,
    },
    {
      id: 'angry',
      label: 'Angry',
      description: 'Protective energy—boundaries, frustration, or threat response.',
      color: GROUP_COLORS.angry,
    },
    {
      id: 'fear',
      label: 'Fear',
      description: 'Threat, uncertainty, or vulnerability states.',
      color: GROUP_COLORS.fear,
    },
  ],

  nodes: [
    // =========================
    // HAPPY
    // =========================
    {
      id: 'happy',
      label: 'Happy',
      level: 0,
      groupId: 'happy',
      parentId: null,
      description: 'A pleasant state—often energized, connected, or satisfied.',
      synonyms: ['cheerful', 'uplifted', 'bright'],
    },

    {
      id: 'happy_joyful',
      label: 'Joyful',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Bright happiness with high energy or delight.',
      synonyms: ['delighted', 'elated', 'overjoyed'],
    },
    {
      id: 'happy_joyful_liberated',
      label: 'Liberated',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_joyful',
      description: 'Feeling free from pressure, worry, or constraints.',
      synonyms: ['unburdened', 'released', 'free'],
    },
    {
      id: 'happy_joyful_ecstatic',
      label: 'Ecstatic',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_joyful',
      description: 'Intense joy or excitement that feels overwhelming.',
      synonyms: ['euphoric', 'thrilled', 'blissed-out'],
    },

    {
      id: 'happy_interested',
      label: 'Interested',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Engaged attention; wanting to learn or explore.',
      synonyms: ['intrigued', 'engaged', 'absorbed'],
    },
    {
      id: 'happy_interested_inquisitive',
      label: 'Inquisitive',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_interested',
      description: 'Wanting to investigate, understand, or ask questions.',
      synonyms: ['questioning', 'probing', 'investigative'],
    },
    {
      id: 'happy_interested_curious',
      label: 'Curious',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_interested',
      description: 'Open to discovery; drawn to what’s unknown.',
      synonyms: ['wondering', 'exploratory', 'nosy'],
    },

    {
      id: 'happy_proud',
      label: 'Proud',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Good self-regard about effort, growth, or achievement.',
      synonyms: ['accomplished', 'fulfilled', 'satisfied'],
    },
    {
      id: 'happy_proud_confident',
      label: 'Confident',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_proud',
      description: 'Trusting your ability to handle what’s in front of you.',
      synonyms: ['assured', 'self-possessed', 'certain'],
    },
    {
      id: 'happy_proud_valued',
      label: 'Valued',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_proud',
      description: 'Feeling recognized, appreciated, and important to others.',
      synonyms: ['respected', 'appreciated', 'cherished'],
    },

    {
      id: 'happy_accepted',
      label: 'Accepted',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Feeling included and welcomed as you are.',
      synonyms: ['welcomed', 'included', 'embraced'],
    },
    {
      id: 'happy_accepted_accepted',
      label: 'Accepted',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_accepted',
      description: 'Belonging without needing to change yourself.',
      synonyms: ['received', 'recognized', 'validated'],
    },
    {
      id: 'happy_accepted_approved',
      label: 'Approved',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_accepted',
      description: 'Feeling affirmed, supported, or endorsed.',
      synonyms: ['affirmed', 'praised', 'supported'],
    },

    {
      id: 'happy_powerful',
      label: 'Powerful',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'A sense of agency and capability.',
      synonyms: ['capable', 'strong', 'in-control'],
    },
    {
      id: 'happy_powerful_empowered',
      label: 'Empowered',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_powerful',
      description: 'Feeling able to act and make choices.',
      synonyms: ['enabled', 'activated', 'supported'],
    },
    {
      id: 'happy_powerful_courageous',
      label: 'Courageous',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_powerful',
      description: 'Willing to face something difficult with intention.',
      synonyms: ['brave', 'bold', 'daring'],
    },

    {
      id: 'happy_intimate',
      label: 'Intimate',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Feeling close, connected, and emotionally near.',
      synonyms: ['close', 'bonded', 'attached'],
    },
    {
      id: 'happy_intimate_playful',
      label: 'Playful',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_intimate',
      description: 'Light, fun, and open to spontaneity.',
      synonyms: ['lighthearted', 'silly', 'goofy'],
    },
    {
      id: 'happy_intimate_sensitive',
      label: 'Sensitive',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_intimate',
      description: 'Tender, emotionally responsive, easily moved.',
      synonyms: ['tender', 'soft', 'openhearted'],
    },

    {
      id: 'happy_appreciative',
      label: 'Appreciative',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Noticing what’s good—gratitude and warm regard.',
      synonyms: ['grateful', 'thankful-hearted', 'touched'],
    },
    {
      id: 'happy_appreciative_thankful',
      label: 'Thankful',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_appreciative',
      description: 'Gratitude for support, luck, or kindness.',
      synonyms: ['grateful', 'appreciative', 'fortunate'],
    },
    {
      id: 'happy_appreciative_loving',
      label: 'Loving',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_appreciative',
      description: 'Warm affection and care toward someone or something.',
      synonyms: ['affectionate', 'caring', 'fond'],
    },

    {
      id: 'happy_optimistic',
      label: 'Optimistic',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Expecting good outcomes; seeing possibility.',
      synonyms: ['upbeat', 'positive', 'forward-looking'],
    },
    {
      id: 'happy_optimistic_inspired',
      label: 'Inspired',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_optimistic',
      description: 'Energized by an idea, purpose, or vision.',
      synonyms: ['motivated', 'sparked', 'fired-up'],
    },
    {
      id: 'happy_optimistic_hopeful',
      label: 'Hopeful',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_optimistic',
      description: 'Believing improvement is possible.',
      synonyms: ['encouraged', 'expectant', 'bright-eyed'],
    },

    {
      id: 'happy_playful',
      label: 'Playful',
      level: 1,
      groupId: 'happy',
      parentId: 'happy',
      description: 'Fun, teasing, or light social energy.',
      synonyms: ['cheeky', 'fun-loving', 'breezy'],
    },
    {
      id: 'happy_playful_animated',
      label: 'Animated',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_playful',
      description: 'Lively, expressive, full of energy.',
      synonyms: ['lively', 'vivacious', 'bouncy'],
    },
    {
      id: 'happy_playful_flirty',
      label: 'Flirty',
      level: 2,
      groupId: 'happy',
      parentId: 'happy_playful',
      description: 'Playful attraction or charming social signaling.',
      synonyms: ['teasing', 'charming', 'coquettish'],
    },

    // =========================
    // SURPRISED
    // =========================
    {
      id: 'surprised',
      label: 'Surprised',
      level: 0,
      groupId: 'surprised',
      parentId: null,
      description: 'A response to something unexpected.',
      synonyms: ['caught-off-guard', 'unexpected', 'taken-aback'],
    },

    {
      id: 'surprised_startled',
      label: 'Startled',
      level: 1,
      groupId: 'surprised',
      parentId: 'surprised',
      description: 'A sudden jolt of attention or alarm.',
      synonyms: ['jolted', 'spooked', 'shaken'],
    },
    {
      id: 'surprised_startled_dismayed',
      label: 'Dismayed',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_startled',
      description: 'Surprise that feels discouraging or unsettling.',
      synonyms: ['disheartened', 'crestfallen', 'alarmed'],
    },
    {
      id: 'surprised_startled_shocked',
      label: 'Shocked',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_startled',
      description: 'Strong surprise that temporarily overwhelms.',
      synonyms: ['stunned', 'speechless', 'floored'],
    },

    {
      id: 'surprised_confused',
      label: 'Confused',
      level: 1,
      groupId: 'surprised',
      parentId: 'surprised',
      description: 'Not sure what’s happening or what it means.',
      synonyms: ['puzzled', 'mixed-up', 'lost'],
    },
    {
      id: 'surprised_confused_disoriented',
      label: 'Disoriented',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_confused',
      description: 'Feeling turned around; losing your bearings.',
      synonyms: ['dazed', 'off-balance', 'turned-around'],
    },
    {
      id: 'surprised_confused_uncertain',
      label: 'Uncertain',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_confused',
      description: 'Not sure what to expect or decide.',
      synonyms: ['unsure', 'in-doubt', 'wavering'],
    },

    {
      id: 'surprised_amazed',
      label: 'Amazed',
      level: 1,
      groupId: 'surprised',
      parentId: 'surprised',
      description: 'Surprise with admiration or wonder.',
      synonyms: ['impressed', 'wow-ed', 'wonderstruck'],
    },
    {
      id: 'surprised_amazed_astonished',
      label: 'Astonished',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_amazed',
      description: 'High-intensity surprise with strong impact.',
      synonyms: ['astounded', 'staggered', 'stunned'],
    },
    {
      id: 'surprised_amazed_awestruck',
      label: 'Awestruck',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_amazed',
      description: 'Overwhelmed by wonder or greatness.',
      synonyms: ['in-awe', 'reverent', 'marveling'],
    },

    {
      id: 'surprised_excited',
      label: 'Excited',
      level: 1,
      groupId: 'surprised',
      parentId: 'surprised',
      description: 'Activated energy from something new or coming soon.',
      synonyms: ['pumped', 'amped', 'stoked'],
    },
    {
      id: 'surprised_excited_eager',
      label: 'Eager',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_excited',
      description: 'Wanting something to happen soon.',
      synonyms: ['keen', 'enthusiastic', 'ready'],
    },
    {
      id: 'surprised_excited_energetic',
      label: 'Energetic',
      level: 2,
      groupId: 'surprised',
      parentId: 'surprised_excited',
      description: 'High physical or mental energy.',
      synonyms: ['charged', 'revved', 'active'],
    },

    // =========================
    // CALM
    // =========================
    {
      id: 'calm',
      label: 'Calm',
      level: 0,
      groupId: 'calm',
      parentId: null,
      description: 'Steady, low-stress, and at ease.',
      synonyms: ['tranquil', 'serene', 'at-ease'],
    },

    {
      id: 'calm_settled',
      label: 'Settled',
      level: 1,
      groupId: 'calm',
      parentId: 'calm',
      description: 'Inner steadiness; not shaken.',
      synonyms: ['stable', 'even', 'untroubled'],
    },
    {
      id: 'calm_settled_grounded',
      label: 'Grounded',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_settled',
      description: 'Connected to the present and to yourself.',
      synonyms: ['anchored', 'rooted', 'centered'],
    },
    {
      id: 'calm_settled_steady',
      label: 'Steady',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_settled',
      description: 'Consistent and balanced; not swinging.',
      synonyms: ['constant', 'firm', 'reliable'],
    },

    {
      id: 'calm_safe',
      label: 'Safe',
      level: 1,
      groupId: 'calm',
      parentId: 'calm',
      description: 'A sense of protection and low threat.',
      synonyms: ['sheltered', 'protected', 'assured'],
    },
    {
      id: 'calm_safe_protected',
      label: 'Protected',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_safe',
      description: 'Buffered from harm or pressure.',
      synonyms: ['shielded', 'covered', 'looked-after'],
    },
    {
      id: 'calm_safe_secure',
      label: 'Secure',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_safe',
      description: 'Stable enough to relax; not bracing.',
      synonyms: ['safe', 'solid', 'grounded-in'],
    },

    {
      id: 'calm_present',
      label: 'Present',
      level: 1,
      groupId: 'calm',
      parentId: 'calm',
      description: 'Here now—attention in the moment.',
      synonyms: ['aware', 'here', 'tuned-in'],
    },
    {
      id: 'calm_present_mindful',
      label: 'Mindful',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_present',
      description: 'Observing with attention and gentleness.',
      synonyms: ['observant', 'noticing', 'aware'],
    },
    {
      id: 'calm_present_attentive',
      label: 'Attentive',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_present',
      description: 'Engaged attention without strain.',
      synonyms: ['alert', 'listening', 'focused'],
    },

    {
      id: 'calm_balanced',
      label: 'Balanced',
      level: 1,
      groupId: 'calm',
      parentId: 'calm',
      description: 'Even, centered, not pulled to extremes.',
      synonyms: ['equable', 'measured', 'stable'],
    },
    {
      id: 'calm_balanced_centered',
      label: 'Centered',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_balanced',
      description: 'Aligned and collected internally.',
      synonyms: ['aligned', 'poised', 'collected'],
    },
    {
      id: 'calm_balanced_composed',
      label: 'Composed',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_balanced',
      description: 'Calm control; not rattled.',
      synonyms: ['unruffled', 'cool-headed', 'contained'],
    },

    {
      id: 'calm_rested',
      label: 'Rested',
      level: 1,
      groupId: 'calm',
      parentId: 'calm',
      description: 'Replenished energy and reduced strain.',
      synonyms: ['recharged', 'renewed', 'reset'],
    },
    {
      id: 'calm_rested_restored',
      label: 'Restored',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_rested',
      description: 'Back to baseline after stress or effort.',
      synonyms: ['recovered', 'revived', 'renewed'],
    },
    {
      id: 'calm_rested_refreshed',
      label: 'Refreshed',
      level: 2,
      groupId: 'calm',
      parentId: 'calm_rested',
      description: 'Lightness and clarity after rest.',
      synonyms: ['revitalized', 'brightened', 'cleared'],
    },

    // =========================
    // SAD
    // =========================
    {
      id: 'sad',
      label: 'Sad',
      level: 0,
      groupId: 'sad',
      parentId: null,
      description: 'Heaviness, loss, or low energy.',
      synonyms: ['down', 'blue', 'heavy-hearted'],
    },

    {
      id: 'sad_guilty',
      label: 'Guilty',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'Feeling you did something wrong or fell short of your values.',
      synonyms: ['regretful', 'self-blaming', 'contrite'],
    },
    {
      id: 'sad_guilty_ashamed',
      label: 'Ashamed',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_guilty',
      description: 'Feeling exposed or not good enough in others’ eyes.',
      synonyms: ['embarrassed-inside', 'self-conscious', 'mortified'],
    },
    {
      id: 'sad_guilty_remorseful',
      label: 'Remorseful',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_guilty',
      description: 'Deep regret and wanting to make amends.',
      synonyms: ['regretful', 'sorry', 'penitent'],
    },

    {
      id: 'sad_abandoned',
      label: 'Abandoned',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'Feeling left alone or unsupported when you needed someone.',
      synonyms: ['left-behind', 'forsaken', 'unsupported'],
    },
    {
      id: 'sad_abandoned_ignored',
      label: 'Ignored',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_abandoned',
      description: 'Feeling unseen or not acknowledged.',
      synonyms: ['overlooked', 'dismissed', 'passed-over'],
    },
    {
      id: 'sad_abandoned_victimized',
      label: 'Victimized',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_abandoned',
      description: 'Feeling harmed or treated unfairly.',
      synonyms: ['wronged', 'mistreated', 'targeted'],
    },

    {
      id: 'sad_despair',
      label: 'Despair',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'A sense that things won’t get better.',
      synonyms: ['hopeless', 'despondent', 'defeated'],
    },
    {
      id: 'sad_despair_powerless',
      label: 'Powerless',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_despair',
      description: 'Feeling like you can’t influence what happens.',
      synonyms: ['helpless', 'stuck', 'trapped'],
    },
    {
      id: 'sad_despair_vulnerable',
      label: 'Vulnerable',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_despair',
      description: 'Feeling exposed, tender, or easily hurt.',
      synonyms: ['exposed', 'tender', 'fragile'],
    },

    {
      id: 'sad_depressed',
      label: 'Depressed',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'Low mood and low energy that can feel heavy or blank.',
      synonyms: ['downcast', 'flattened', 'drained'],
    },
    {
      id: 'sad_depressed_numb',
      label: 'Numb',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_depressed',
      description: 'Feeling emotionally muted or shut down.',
      synonyms: ['blank', 'muted', 'frozen'],
    },
    {
      id: 'sad_depressed_empty',
      label: 'Empty',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_depressed',
      description: 'Feeling hollow or lacking meaning/connection.',
      synonyms: ['hollow', 'vacant', 'void'],
    },

    {
      id: 'sad_lonely',
      label: 'Lonely',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'Wanting connection and not having it.',
      synonyms: ['alone', 'disconnected', 'isolated-inside'],
    },
    {
      id: 'sad_lonely_isolated',
      label: 'Isolated',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_lonely',
      description: 'Cut off from people or support.',
      synonyms: ['separated', 'cut-off', 'apart'],
    },
    {
      id: 'sad_lonely_unseen',
      label: 'Unseen',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_lonely',
      description: 'Feeling not recognized or not understood.',
      synonyms: ['unnoticed', 'unrecognized', 'misunderstood'],
    },

    {
      id: 'sad_bored',
      label: 'Bored',
      level: 1,
      groupId: 'sad',
      parentId: 'sad',
      description: 'Low stimulation; nothing feels engaging right now.',
      synonyms: ['uninvolved', 'under-stimulated', 'meh'],
    },
    {
      id: 'sad_bored_listless',
      label: 'Listless',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_bored',
      description: 'Low energy and motivation; dragging.',
      synonyms: ['lethargic', 'sluggish', 'drained'],
    },
    {
      id: 'sad_bored_unstimulated',
      label: 'Unstimulated',
      level: 2,
      groupId: 'sad',
      parentId: 'sad_bored',
      description: 'Not mentally engaged; needing novelty or meaning.',
      synonyms: ['unengaged', 'uninterested', 'unoccupied'],
    },

    // =========================
    // DISGUSTED
    // =========================
    {
      id: 'disgusted',
      label: 'Disgusted',
      level: 0,
      groupId: 'disgusted',
      parentId: null,
      description: 'Aversion, rejection, or emotional recoil.',
      synonyms: ['grossed-out', 'put-off', 'turned-off'],
    },

    {
      id: 'disgusted_disapproval',
      label: 'Disapproval',
      level: 1,
      groupId: 'disgusted',
      parentId: 'disgusted',
      description: 'A moral or value-based ‘no’ reaction.',
      synonyms: ['disapproving', 'critical-minded', 'displeased'],
    },
    {
      id: 'disgusted_disapproval_judgmental',
      label: 'Judgmental',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disapproval',
      description: 'Harsh evaluation of someone’s actions or choices.',
      synonyms: ['fault-finding', 'condemning', 'strict'],
    },
    {
      id: 'disgusted_disapproval_contemptuous',
      label: 'Contemptuous',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disapproval',
      description: 'Looking down on someone with strong disapproval.',
      synonyms: ['scornful', 'derisive', 'sneering'],
    },

    {
      id: 'disgusted_disappointment',
      label: 'Disappointment',
      level: 1,
      groupId: 'disgusted',
      parentId: 'disgusted',
      description: 'A strong ‘no’ reaction that makes you want distance.',
      synonyms: ['put-off', 'repulsed', 'soured'],
    },
    {
      id: 'disgusted_disappointment_repelled',
      label: 'Repelled',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disappointment',
      description: 'Feeling pushed away; wanting to create distance.',
      synonyms: ['driven-away', 'pushed-back', 'averse-feeling'],
    },
    {
      id: 'disgusted_disappointment_revolted',
      label: 'Revolted',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disappointment',
      description: 'Strong disgust that feels intense or visceral.',
      synonyms: ['sickened', 'queasy', 'grossed-out'],
    },

    {
      id: 'disgusted_disturbed',
      label: 'Disturbed',
      level: 1,
      groupId: 'disgusted',
      parentId: 'disgusted',
      description: 'Uncomfortable emotional recoil; something feels off.',
      synonyms: ['bothered', 'uneasy-inside', 'uncomfortable'],
    },
    {
      id: 'disgusted_disturbed_uneasy',
      label: 'Uneasy',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disturbed',
      description: 'A subtle sense of discomfort or worry.',
      synonyms: ['ill-at-ease', 'restless', 'edgy'],
    },
    {
      id: 'disgusted_disturbed_unsettled',
      label: 'Unsettled',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_disturbed',
      description: 'Not stable; emotionally thrown off.',
      synonyms: ['shaken-up', 'off-kilter', 'rattled'],
    },

    {
      id: 'disgusted_avoidant',
      label: 'Avoidant',
      level: 1,
      groupId: 'disgusted',
      parentId: 'disgusted',
      description: 'Pulling away to protect your comfort or boundaries.',
      synonyms: ['withdrawing', 'keeping-distance', 'reserved'],
    },
    {
      id: 'disgusted_avoidant_averse',
      label: 'Averse',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_avoidant',
      description: 'Not wanting contact with something; strongly disinclined.',
      synonyms: ['disinclined', 'reluctant', 'opposed'],
    },
    {
      id: 'disgusted_avoidant_hesitant',
      label: 'Hesitant',
      level: 2,
      groupId: 'disgusted',
      parentId: 'disgusted_avoidant',
      description: 'Holding back; not ready to engage.',
      synonyms: ['unsure', 'tentative', 'paused'],
    },

    // =========================
    // ANGRY
    // =========================
    {
      id: 'angry',
      label: 'Angry',
      level: 0,
      groupId: 'angry',
      parentId: null,
      description: 'Protective energy around boundaries, fairness, or threat.',
      synonyms: ['mad-at', 'worked-up', 'heated'],
    },

    {
      id: 'angry_hurt',
      label: 'Hurt',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Pain from rejection, insult, or emotional injury.',
      synonyms: ['wounded', 'stung', 'pained'],
    },
    {
      id: 'angry_hurt_devastated',
      label: 'Devastated',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_hurt',
      description: 'Overwhelming emotional impact; knocked down.',
      synonyms: ['crushed', 'shattered', 'heartbroken'],
    },
    {
      id: 'angry_hurt_embarrassed',
      label: 'Embarrassed',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_hurt',
      description: 'Self-conscious discomfort in a social moment.',
      synonyms: ['awkward', 'flustered', 'self-conscious'],
    },

    {
      id: 'angry_threatened',
      label: 'Threatened',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Sensing danger to status, safety, or relationship.',
      synonyms: ['at-risk', 'on-edge', 'defensive'],
    },
    {
      id: 'angry_threatened_jealous',
      label: 'Jealous',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_threatened',
      description: 'Fear of losing attention, affection, or connection.',
      synonyms: ['possessive', 'envious', 'protective'],
    },
    {
      id: 'angry_threatened_guarded',
      label: 'Guarded',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_threatened',
      description: 'Protecting yourself by holding back.',
      synonyms: ['defended', 'closed-off', 'wary'],
    },

    {
      id: 'angry_hateful',
      label: 'Hateful',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Strong hostility and rejection toward someone or something.',
      synonyms: ['spiteful', 'bitter', 'full-of-anger'],
    },
    {
      id: 'angry_hateful_violated',
      label: 'Violated',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_hateful',
      description: 'Feeling your boundaries were crossed.',
      synonyms: ['disrespected', 'exposed', 'unsafe'],
    },
    {
      id: 'angry_hateful_resentful',
      label: 'Resentful',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_hateful',
      description: 'Carrying anger over something unfair or unresolved.',
      synonyms: ['bitter', 'aggrieved', 'sore'],
    },

    {
      id: 'angry_mad',
      label: 'Mad',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Direct anger; strong irritation or outrage.',
      synonyms: ['furious-inside', 'heated', 'irate'],
    },
    {
      id: 'angry_mad_enraged',
      label: 'Enraged',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_mad',
      description: 'Very intense anger; hard to contain.',
      synonyms: ['incensed', 'outraged', 'seething'],
    },
    {
      id: 'angry_mad_furious',
      label: 'Furious',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_mad',
      description: 'Explosive-feeling anger; hot and intense.',
      synonyms: ['livid', 'irate', 'steam'],
    },

    {
      id: 'angry_aggressive',
      label: 'Aggressive',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Anger with a push-forward or confrontational edge.',
      synonyms: ['confrontational', 'forceful', 'pushy'],
    },
    {
      id: 'angry_aggressive_provoked',
      label: 'Provoked',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_aggressive',
      description: 'Feeling pushed into reacting.',
      synonyms: ['pushed', 'baited', 'triggered'],
    },
    {
      id: 'angry_aggressive_hostile',
      label: 'Hostile',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_aggressive',
      description: 'Cold or tense opposition toward someone.',
      synonyms: ['antagonistic', 'unfriendly', 'combative'],
    },

    {
      id: 'angry_frustrated',
      label: 'Frustrated',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Blocked goals; effort meets resistance.',
      synonyms: ['stuck', 'thwarted', 'exasperated'],
    },
    {
      id: 'angry_frustrated_irritated',
      label: 'Irritated',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_frustrated',
      description: 'Mild-to-moderate annoyance.',
      synonyms: ['annoyed', 'bothered', 'peeved'],
    },
    {
      id: 'angry_frustrated_infuriated',
      label: 'Infuriated',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_frustrated',
      description: 'Strong anger sparked by something unfair or aggravating.',
      synonyms: ['enflamed', 'incensed', 'outraged'],
    },

    {
      id: 'angry_distant',
      label: 'Distant',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Pulling away emotionally; keeping space.',
      synonyms: ['removed', 'detached', 'cool'],
    },
    {
      id: 'angry_distant_suspicious',
      label: 'Suspicious',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_distant',
      description: 'Doubting intentions; expecting harm or deception.',
      synonyms: ['distrustful', 'skeptical', 'wary'],
    },
    {
      id: 'angry_distant_withdrawn',
      label: 'Withdrawn',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_distant',
      description: 'Stepping back; lowering contact or engagement.',
      synonyms: ['pulled-back', 'retreated', 'closed-off'],
    },

    {
      id: 'angry_critical',
      label: 'Critical',
      level: 1,
      groupId: 'angry',
      parentId: 'angry',
      description: 'Irritated judgment; focused on flaws or problems.',
      synonyms: ['judging', 'fault-finding', 'nitpicky'],
    },
    {
      id: 'angry_critical_sarcastic',
      label: 'Sarcastic',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_critical',
      description: 'Sharp humor used to express annoyance.',
      synonyms: ['snide', 'wry', 'mocking'],
    },
    {
      id: 'angry_critical_dismissive',
      label: 'Dismissive',
      level: 2,
      groupId: 'angry',
      parentId: 'angry_critical',
      description: 'Minimizing someone or pushing them away emotionally.',
      synonyms: ['brushing-off', 'minimizing', 'cold'],
    },

    // =========================
    // FEAR
    // =========================
    {
      id: 'fear',
      label: 'Fear',
      level: 0,
      groupId: 'fear',
      parentId: null,
      description: 'Threat, uncertainty, or vulnerability.',
      synonyms: ['afraid', 'nervous', 'spooked'],
    },

    {
      id: 'fear_anxious',
      label: 'Anxious',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Worry plus body activation; anticipating problems.',
      synonyms: ['nervous', 'uneasy', 'on-edge'],
    },
    {
      id: 'fear_anxious_overwhelmed',
      label: 'Overwhelmed',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_anxious',
      description: 'Too much at once; capacity feels exceeded.',
      synonyms: ['swamped', 'flooded', 'overloaded'],
    },
    {
      id: 'fear_anxious_worried',
      label: 'Worried',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_anxious',
      description: 'Concern about what might happen.',
      synonyms: ['concerned', 'uneasy', 'apprehensive'],
    },

    {
      id: 'fear_scared',
      label: 'Scared',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Feeling threatened; wanting safety.',
      synonyms: ['afraid', 'spooked', 'alarmed'],
    },
    {
      id: 'fear_scared_frightened',
      label: 'Frightened',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_scared',
      description: 'Fear that feels sharp and immediate.',
      synonyms: ['startled', 'spooked', 'alarmed'],
    },
    {
      id: 'fear_scared_terrified',
      label: 'Terrified',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_scared',
      description: 'Very intense fear; panic-like intensity.',
      synonyms: ['panic-stricken', 'petrified', 'frozen-with-fear'],
    },

    {
      id: 'fear_insecure',
      label: 'Insecure',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Doubting yourself; feeling not enough.',
      synonyms: ['self-doubting', 'uncertain-of-self', 'shaky'],
    },
    {
      id: 'fear_insecure_inferior',
      label: 'Inferior',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_insecure',
      description: 'Feeling lesser-than or not measuring up.',
      synonyms: ['second-best', 'less-than', 'not-good-enough'],
    },
    {
      id: 'fear_insecure_inadequate',
      label: 'Inadequate',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_insecure',
      description: 'Feeling unprepared or insufficient for the situation.',
      synonyms: ['unready', 'unequipped', 'underqualified'],
    },

    {
      id: 'fear_submissive',
      label: 'Submissive',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Shrinking back; lowering your needs to avoid conflict.',
      synonyms: ['yielding', 'meek', 'over-accommodating'],
    },
    {
      id: 'fear_submissive_insignificant',
      label: 'Insignificant',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_submissive',
      description: 'Feeling small or unimportant in the moment.',
      synonyms: ['small', 'invisible', 'overlooked'],
    },
    {
      id: 'fear_submissive_devalued',
      label: 'Devalued',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_submissive',
      description: 'Feeling not appreciated or not treated with respect.',
      synonyms: ['discounted', 'unappreciated', 'minimized'],
    },

    {
      id: 'fear_rejected',
      label: 'Rejected',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Social pain from exclusion or dismissal.',
      synonyms: ['left-out', 'shut-out', 'cast-aside'],
    },
    {
      id: 'fear_rejected_excluded',
      label: 'Excluded',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_rejected',
      description: 'Not included; outside the group or connection.',
      synonyms: ['left-out', 'shut-out', 'passed-over'],
    },
    {
      id: 'fear_rejected_unwanted',
      label: 'Unwanted',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_rejected',
      description: 'Feeling like your presence or needs aren’t desired.',
      synonyms: ['unwelcome', 'unneeded', 'pushed-away'],
    },

    {
      id: 'fear_humiliated',
      label: 'Humiliated',
      level: 1,
      groupId: 'fear',
      parentId: 'fear',
      description: 'Feeling exposed, shamed, or lowered publicly.',
      synonyms: ['mortified', 'made-small', 'embarrassed-publicly'],
    },
    {
      id: 'fear_humiliated_ridiculed',
      label: 'Ridiculed',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_humiliated',
      description: 'Feeling mocked or laughed at.',
      synonyms: ['made-fun-of', 'teased', 'laughed-at'],
    },
    {
      id: 'fear_humiliated_disrespected',
      label: 'Disrespected',
      level: 2,
      groupId: 'fear',
      parentId: 'fear_humiliated',
      description: 'Feeling your dignity or boundaries weren’t honored.',
      synonyms: ['dismissed', 'undermined', 'talked-down-to'],
    },
  ],
};
