import type { EmotionGroup, EmotionNode } from '../types';

export const angryGroup: EmotionGroup = {
  id: 'angry',
  label: 'Angry',
  description: 'Protective energy—boundaries, frustration, or threat response.',
  color: '#ff1744',
};

const rawAngryNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'angry',
    label: 'Angry',
    level: 0,
    groupId: 'angry',
    parentId: null,
    description: 'Protective energy around boundaries, fairness, or threat.',
    synonyms: ['mad-at', 'worked-up', 'heated'],
  },
  {
    id: 'angry_hurt',
    label: 'Hurt',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Pain from rejection, insult, or emotional injury.',
    synonyms: ['wounded', 'stung', 'pained'],
  },
  {
    id: 'angry_hurt_devastated',
    label: 'Devastated',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_hurt',
    description: 'Overwhelming emotional impact; knocked down.',
    synonyms: ['crushed', 'shattered', 'heartbroken'],
  },
  {
    id: 'angry_hurt_embarrassed',
    label: 'Embarrassed',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_hurt',
    description: 'Self-conscious discomfort in a social moment.',
    synonyms: ['awkward', 'flustered', 'self-conscious'],
  },
  {
    id: 'angry_threatened',
    label: 'Threatened',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Sensing danger to status, safety, or relationship.',
    synonyms: ['at-risk', 'on-edge', 'defensive'],
  },
  {
    id: 'angry_threatened_jealous',
    label: 'Jealous',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_threatened',
    description: 'Fear of losing attention, affection, or connection.',
    synonyms: ['possessive', 'envious', 'protective'],
  },
  {
    id: 'angry_threatened_guarded',
    label: 'Guarded',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_threatened',
    description: 'Protecting yourself by holding back.',
    synonyms: ['defended', 'closed-off', 'wary'],
  },
  {
    id: 'angry_hateful',
    label: 'Hateful',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Strong hostility and rejection toward someone or something.',
    synonyms: ['spiteful', 'bitter', 'full-of-anger'],
  },
  {
    id: 'angry_hateful_violated',
    label: 'Violated',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_hateful',
    description: 'Feeling your boundaries were crossed.',
    synonyms: ['disrespected', 'exposed', 'unsafe'],
  },
  {
    id: 'angry_hateful_resentful',
    label: 'Resentful',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_hateful',
    description: 'Carrying anger over something unfair or unresolved.',
    synonyms: ['bitter', 'aggrieved', 'sore'],
  },
  {
    id: 'angry_mad',
    label: 'Mad',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Direct anger; strong irritation or outrage.',
    synonyms: ['furious-inside', 'heated', 'irate'],
  },
  {
    id: 'angry_mad_enraged',
    label: 'Enraged',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_mad',
    description: 'Very intense anger; hard to contain.',
    synonyms: ['incensed', 'outraged', 'seething'],
  },
  {
    id: 'angry_mad_furious',
    label: 'Furious',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_mad',
    description: 'Explosive-feeling anger; hot and intense.',
    synonyms: ['livid', 'irate', 'steaming'],
  },
  {
    id: 'angry_aggressive',
    label: 'Aggressive',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Anger with a push-forward or confrontational edge.',
    synonyms: ['confrontational', 'forceful', 'pushy'],
  },
  {
    id: 'angry_aggressive_provoked',
    label: 'Provoked',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_aggressive',
    description: 'Feeling pushed into reacting.',
    synonyms: ['pushed', 'baited', 'triggered'],
  },
  {
    id: 'angry_aggressive_hostile',
    label: 'Hostile',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_aggressive',
    description: 'Cold or tense opposition toward someone.',
    synonyms: ['antagonistic', 'unfriendly', 'combative'],
  },
  {
    id: 'angry_frustrated',
    label: 'Frustrated',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Blocked goals; effort meets resistance.',
    synonyms: ['stuck', 'thwarted', 'exasperated'],
  },
  {
    id: 'angry_frustrated_irritated',
    label: 'Irritated',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_frustrated',
    description: 'Mild-to-moderate annoyance.',
    synonyms: ['annoyed', 'bothered', 'peeved'],
  },
  {
    id: 'angry_frustrated_infuriated',
    label: 'Infuriated',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_frustrated',
    description: 'Strong anger sparked by something unfair or aggravating.',
    synonyms: ['enflamed', 'incensed', 'outraged'],
  },
  {
    id: 'angry_distant',
    label: 'Distant',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Pulling away emotionally; keeping space.',
    synonyms: ['removed', 'detached', 'cool'],
  },
  {
    id: 'angry_distant_suspicious',
    label: 'Suspicious',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_distant',
    description: 'Doubting intentions; expecting harm or deception.',
    synonyms: ['distrustful', 'skeptical', 'wary'],
  },
  {
    id: 'angry_distant_withdrawn',
    label: 'Withdrawn',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_distant',
    description: 'Stepping back; lowering contact or engagement.',
    synonyms: ['pulled-back', 'retreated', 'closed-off'],
  },
  {
    id: 'angry_critical',
    label: 'Critical',
    level: 1,
    groupId: 'angry',
    parentId: 'angry',
    description: 'Irritated judgment; focused on flaws or problems.',
    synonyms: ['judging', 'fault-finding', 'nitpicky'],
  },
  {
    id: 'angry_critical_sarcastic',
    label: 'Sarcastic',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_critical',
    description: 'Sharp humor used to express annoyance.',
    synonyms: ['snide', 'wry', 'mocking'],
  },
  {
    id: 'angry_critical_dismissive',
    label: 'Dismissive',
    level: 2,
    groupId: 'angry',
    parentId: 'angry_critical',
    description: 'Minimizing someone or pushing them away emotionally.',
    synonyms: ['brushing-off', 'minimizing', 'cold'],
  },
];

export const angryNodes = rawAngryNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
