import type { EmotionGroup, EmotionNode } from '../types';

export const calmGroup: EmotionGroup = {
  id: 'calm',
  label: 'Calm',
  description: 'Settled, steady states with low threat and ease.',
  color: '#4caf50',
};

const rawCalmNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'calm',
    label: 'Calm',
    level: 0,
    groupId: 'calm',
    parentId: null,
    description: 'Steady, low-stress, and at ease.',
    synonyms: ['tranquil', 'serene', 'at-ease'],
  },
  {
    id: 'calm_settled',
    label: 'Settled',
    level: 1,
    groupId: 'calm',
    parentId: 'calm',
    description: 'Inner steadiness; not shaken.',
    synonyms: ['stable', 'even', 'untroubled'],
  },
  {
    id: 'calm_settled_grounded',
    label: 'Grounded',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_settled',
    description: 'Connected to the present and to yourself.',
    synonyms: ['anchored', 'rooted', 'centered'],
  },
  {
    id: 'calm_settled_steady',
    label: 'Steady',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_settled',
    description: 'Consistent and balanced; not swinging.',
    synonyms: ['constant', 'firm', 'reliable'],
  },
  {
    id: 'calm_safe',
    label: 'Safe',
    level: 1,
    groupId: 'calm',
    parentId: 'calm',
    description: 'A sense of protection and low threat.',
    synonyms: ['sheltered', 'protected', 'assured'],
  },
  {
    id: 'calm_safe_protected',
    label: 'Protected',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_safe',
    description: 'Buffered from harm or pressure.',
    synonyms: ['shielded', 'covered', 'looked-after'],
  },
  {
    id: 'calm_safe_secure',
    label: 'Secure',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_safe',
    description: 'Stable enough to relax; not bracing.',
    synonyms: ['safe', 'solid', 'grounded-in'],
  },
  {
    id: 'calm_present',
    label: 'Present',
    level: 1,
    groupId: 'calm',
    parentId: 'calm',
    description: 'Here now—attention in the moment.',
    synonyms: ['aware', 'here', 'tuned-in'],
  },
  {
    id: 'calm_present_mindful',
    label: 'Mindful',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_present',
    description: 'Observing with attention and gentleness.',
    synonyms: ['observant', 'noticing', 'aware'],
  },
  {
    id: 'calm_present_attentive',
    label: 'Attentive',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_present',
    description: 'Engaged attention without strain.',
    synonyms: ['alert', 'listening', 'focused'],
  },
  {
    id: 'calm_balanced',
    label: 'Balanced',
    level: 1,
    groupId: 'calm',
    parentId: 'calm',
    description: 'Even, centered, not pulled to extremes.',
    synonyms: ['equable', 'measured', 'stable'],
  },
  {
    id: 'calm_balanced_centered',
    label: 'Centered',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_balanced',
    description: 'Aligned and collected internally.',
    synonyms: ['aligned', 'poised', 'collected'],
  },
  {
    id: 'calm_balanced_composed',
    label: 'Composed',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_balanced',
    description: 'Calm control; not rattled.',
    synonyms: ['unruffled', 'cool-headed', 'contained'],
  },
  {
    id: 'calm_rested',
    label: 'Rested',
    level: 1,
    groupId: 'calm',
    parentId: 'calm',
    description: 'Replenished energy and reduced strain.',
    synonyms: ['recharged', 'renewed', 'reset'],
  },
  {
    id: 'calm_rested_restored',
    label: 'Restored',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_rested',
    description: 'Back to baseline after stress or effort.',
    synonyms: ['recovered', 'revived', 'renewed'],
  },
  {
    id: 'calm_rested_refreshed',
    label: 'Refreshed',
    level: 2,
    groupId: 'calm',
    parentId: 'calm_rested',
    description: 'Lightness and clarity after rest.',
    synonyms: ['revitalized', 'brightened', 'cleared'],
  },
];

export const calmNodes = rawCalmNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
