import type { EmotionGroup, EmotionNode } from '../types';

export const disgustedGroup: EmotionGroup = {
  id: 'disgusted',
  label: 'Disgusted',
  description: 'Aversion, rejection, or emotional recoil.',
  color: '#aa00ff',
};

export const rawDisgustedNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'disgusted',
    label: 'Disgusted',
    level: 0,
    groupId: 'disgusted',
    parentId: null,
    description: 'Aversion, rejection, or emotional recoil.',
    synonyms: ['grossed-out', 'put-off', 'turned-off'],
  },
  {
    id: 'disgusted_disapproval',
    label: 'Disapproval',
    level: 1,
    groupId: 'disgusted',
    parentId: 'disgusted',
    description: 'A moral or value-based ‘no’ reaction.',
    synonyms: ['disapproving', 'critical-minded', 'displeased'],
  },
  {
    id: 'disgusted_disapproval_judgmental',
    label: 'Judgmental',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disapproval',
    description: 'Harsh evaluation of someone’s actions or choices.',
    synonyms: ['fault-finding', 'condemning', 'strict'],
  },
  {
    id: 'disgusted_disapproval_contemptuous',
    label: 'Contemptuous',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disapproval',
    description: 'Looking down on someone with strong disapproval.',
    synonyms: ['scornful', 'derisive', 'sneering'],
  },
  {
    id: 'disgusted_disappointment',
    label: 'Disappointment',
    level: 1,
    groupId: 'disgusted',
    parentId: 'disgusted',
    description: 'A strong ‘no’ reaction that makes you want distance.',
    synonyms: ['put-off', 'repulsed', 'soured'],
  },
  {
    id: 'disgusted_disappointment_repelled',
    label: 'Repelled',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disappointment',
    description: 'Feeling pushed away; wanting to create distance.',
    synonyms: ['driven-away', 'pushed-back', 'averse-feeling'],
  },
  {
    id: 'disgusted_disappointment_revolted',
    label: 'Revolted',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disappointment',
    description: 'Strong disgust that feels intense or visceral.',
    synonyms: ['sickened', 'queasy', 'grossed-out'],
  },
  {
    id: 'disgusted_disturbed',
    label: 'Disturbed',
    level: 1,
    groupId: 'disgusted',
    parentId: 'disgusted',
    description: 'Uncomfortable emotional recoil; something feels off.',
    synonyms: ['bothered', 'uneasy-inside', 'uncomfortable'],
  },
  {
    id: 'disgusted_disturbed_uneasy',
    label: 'Uneasy',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disturbed',
    description: 'A subtle sense of discomfort or worry.',
    synonyms: ['ill-at-ease', 'restless', 'edgy'],
  },
  {
    id: 'disgusted_disturbed_unsettled',
    label: 'Unsettled',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_disturbed',
    description: 'Not stable; emotionally thrown off.',
    synonyms: ['shaken-up', 'off-kilter', 'rattled'],
  },
  {
    id: 'disgusted_avoidant',
    label: 'Avoidant',
    level: 1,
    groupId: 'disgusted',
    parentId: 'disgusted',
    description: 'Pulling away to protect your comfort or boundaries.',
    synonyms: ['withdrawing', 'keeping-distance', 'reserved'],
  },
  {
    id: 'disgusted_avoidant_averse',
    label: 'Averse',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_avoidant',
    description: 'Not wanting contact with something; strongly disinclined.',
    synonyms: ['disinclined', 'reluctant', 'opposed'],
  },
  {
    id: 'disgusted_avoidant_hesitant',
    label: 'Hesitant',
    level: 2,
    groupId: 'disgusted',
    parentId: 'disgusted_avoidant',
    description: 'Holding back; not ready to engage.',
    synonyms: ['unsure', 'tentative', 'paused'],
  },
];

export const disgustedNodes = rawDisgustedNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
