import type { EmotionGroup, EmotionNode } from '../types';

export const fearfulGroup: EmotionGroup = {
  id: 'fearful',
  label: 'Fearful',
  description: 'Threat, uncertainty, or vulnerability states.',
  color: '#ff1744',
};

export const rawFearfulNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'fearful',
    label: 'Fearful',
    level: 0,
    groupId: 'fearful',
    parentId: null,
    description: 'Threat, uncertainty, or vulnerability.',
    synonyms: ['afraid', 'nervous', 'spooked'],
  },
  {
    id: 'fear_anxious',
    label: 'Anxious',
    level: 1,
    groupId: 'fearful',
    parentId: 'fearful',
    description: 'Worry plus body activation; anticipating problems.',
    synonyms: ['nervous', 'uneasy', 'on-edge'],
  },
  {
    id: 'fear_anxious_overwhelmed',
    label: 'Overwhelmed',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_anxious',
    description: 'Too much at once; capacity feels exceeded.',
    synonyms: ['swamped', 'flooded', 'overloaded'],
  },
  {
    id: 'fear_anxious_worried',
    label: 'Worried',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_anxious',
    description: 'Concern about what might happen.',
    synonyms: ['concerned', 'uneasy', 'apprehensive'],
  },
  {
    id: 'fear_scared',
    label: 'Scared',
    level: 1,
    groupId: 'fearful',
    parentId: 'fearful',
    description: 'Feeling threatened; wanting safety.',
    synonyms: ['afraid', 'spooked', 'alarmed'],
  },
  {
    id: 'fear_scared_frightened',
    label: 'Frightened',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_scared',
    description: 'Fear that feels sharp and immediate.',
    synonyms: ['startled', 'spooked', 'alarmed'],
  },
  {
    id: 'fear_scared_terrified',
    label: 'Terrified',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_scared',
    description: 'Very intense fear; panic-like intensity.',
    synonyms: ['panic-stricken', 'petrified', 'frozen-with-fear'],
  },
  {
    id: 'fear_insecure',
    label: 'Insecure',
    level: 1,
    groupId: 'fearful',
    parentId: 'fear',
    description: 'Doubting yourself; feeling not enough.',
    synonyms: ['self-doubting', 'uncertain-of-self', 'shaky'],
  },
  {
    id: 'fear_insecure_inferior',
    label: 'Inferior',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_insecure',
    description: 'Feeling lesser-than or not measuring up.',
    synonyms: ['second-best', 'less-than', 'not-good-enough'],
  },
  {
    id: 'fear_insecure_inadequate',
    label: 'Inadequate',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_insecure',
    description: 'Feeling unprepared or insufficient for the situation.',
    synonyms: ['unready', 'unequipped', 'unqualified'],
  },
  {
    id: 'fear_submissive',
    label: 'Submissive',
    level: 1,
    groupId: 'fearful',
    parentId: 'fearful',
    description: 'Shrinking back; lowering your needs to avoid conflict.',
    synonyms: ['yielding', 'meek', 'over-accommodating'],
  },
  {
    id: 'fear_submissive_insignificant',
    label: 'Insignificant',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_submissive',
    description: 'Feeling small or unimportant in the moment.',
    synonyms: ['small', 'invisible', 'overlooked'],
  },
  {
    id: 'fear_submissive_devalued',
    label: 'Devalued',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_submissive',
    description: 'Feeling not appreciated or not treated with respect.',
    synonyms: ['discounted', 'unappreciated', 'minimized'],
  },
  {
    id: 'fear_rejected',
    label: 'Rejected',
    level: 1,
    groupId: 'fearful',
    parentId: 'fearful',
    description: 'Social pain from exclusion or dismissal.',
    synonyms: ['left-out', 'shut-out', 'cast-aside'],
  },
  {
    id: 'fear_rejected_excluded',
    label: 'Excluded',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_rejected',
    description: 'Not included; outside the group or connection.',
    synonyms: ['left-out', 'shut-out', 'passed-over'],
  },
  {
    id: 'fear_rejected_unwanted',
    label: 'Unwanted',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_rejected',
    description: 'Feeling like your presence or needs aren’t desired.',
    synonyms: ['unwelcome', 'unneeded', 'pushed-away'],
  },
  {
    id: 'fear_humiliated',
    label: 'Humiliated',
    level: 1,
    groupId: 'fearful',
    parentId: 'fear',
    description: 'Feeling exposed, shamed, or lowered publicly.',
    synonyms: ['mortified', 'made-small', 'embarrassed-publicly'],
  },
  {
    id: 'fear_humiliated_ridiculed',
    label: 'Ridiculed',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_humiliated',
    description: 'Feeling mocked or laughed at.',
    synonyms: ['made-fun-of', 'teased', 'laughed-at'],
  },
  {
    id: 'fear_humiliated_disrespected',
    label: 'Disrespected',
    level: 2,
    groupId: 'fearful',
    parentId: 'fear_humiliated',
    description: 'Feeling your dignity or boundaries weren’t honored.',
    synonyms: ['dismissed', 'undermined', 'talked-down-to'],
  },
];

export const fearfulNodes = rawFearfulNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
