import type { EmotionGroup, EmotionNode } from '../types';

export const happyGroup: EmotionGroup = {
  id: 'happy',
  label: 'Happy',
  description: 'Pleasant, energized, or connected states.',
  color: '#ffd300',
};

const rawHappyNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'happy',
    label: 'Happy',
    level: 0,
    groupId: 'happy',
    parentId: null,
    description: 'A pleasant state—often energized, connected, or satisfied.',
    synonyms: ['cheerful', 'uplifted', 'bright'],
  },
  {
    id: 'happy_joyful',
    label: 'Joyful',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Bright happiness with high energy or delight.',
    synonyms: ['delighted', 'elated', 'overjoyed'],
  },
  {
    id: 'happy_joyful_liberated',
    label: 'Liberated',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_joyful',
    description: 'Feeling free from pressure, worry, or constraints.',
    synonyms: ['unburdened', 'released', 'free'],
  },
  {
    id: 'happy_joyful_ecstatic',
    label: 'Ecstatic',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_joyful',
    description: 'Intense joy or excitement that feels overwhelming.',
    synonyms: ['euphoric', 'thrilled', 'blissed-out'],
  },
  {
    id: 'happy_interested',
    label: 'Interested',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Engaged attention; wanting to learn or explore.',
    synonyms: ['intrigued', 'engaged', 'absorbed'],
  },
  {
    id: 'happy_interested_inquisitive',
    label: 'Inquisitive',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_interested',
    description: 'Wanting to investigate, understand, or ask questions.',
    synonyms: ['questioning', 'probing', 'investigative'],
  },
  {
    id: 'happy_interested_curious',
    label: 'Curious',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_interested',
    description: 'Open to discovery; drawn to what’s unknown.',
    synonyms: ['wondering', 'exploratory', 'nosy'],
  },
  {
    id: 'happy_proud',
    label: 'Proud',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Good self-regard about effort, growth, or achievement.',
    synonyms: ['accomplished', 'fulfilled', 'satisfied'],
  },
  {
    id: 'happy_proud_confident',
    label: 'Confident',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_proud',
    description: 'Trusting your ability to handle what’s in front of you.',
    synonyms: ['assured', 'self-possessed', 'certain'],
  },
  {
    id: 'happy_proud_valued',
    label: 'Valued',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_proud',
    description: 'Feeling recognized, appreciated, and important to others.',
    synonyms: ['respected', 'appreciated', 'cherished'],
  },
  {
    id: 'happy_accepted',
    label: 'Accepted',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Feeling included and welcomed as you are.',
    synonyms: ['welcomed', 'included', 'embraced'],
  },
  {
    id: 'happy_accepted_validated',
    label: 'Validated',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_accepted',
    description: 'Belonging without needing to change yourself.',
    synonyms: ['received', 'recognized'],
  },
  {
    id: 'happy_accepted_approved',
    label: 'Approved',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_accepted',
    description: 'Feeling affirmed, supported, or endorsed.',
    synonyms: ['affirmed', 'praised', 'supported'],
  },
  {
    id: 'happy_powerful',
    label: 'Powerful',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'A sense of agency and capability.',
    synonyms: ['capable', 'strong', 'in-control'],
  },
  {
    id: 'happy_powerful_empowered',
    label: 'Empowered',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_powerful',
    description: 'Feeling able to act and make choices.',
    synonyms: ['enabled', 'activated', 'supported'],
  },
  {
    id: 'happy_powerful_courageous',
    label: 'Courageous',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_powerful',
    description: 'Willing to face something difficult with intention.',
    synonyms: ['brave', 'bold', 'daring'],
  },
  {
    id: 'happy_intimate',
    label: 'Intimate',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Feeling close, connected, and emotionally near.',
    synonyms: ['close', 'bonded', 'attached'],
  },
  {
    id: 'happy_intimate_playful',
    label: 'Spontaneous',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_intimate',
    description: 'Light, fun, and open to new ideas.',
    synonyms: ['lighthearted', 'silly', 'goofy'],
  },
  {
    id: 'happy_intimate_sensitive',
    label: 'Sensitive',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_intimate',
    description: 'Tender, emotionally responsive, easily moved.',
    synonyms: ['tender', 'soft', 'openhearted'],
  },
  {
    id: 'happy_appreciative',
    label: 'Appreciative',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Noticing what’s good—gratitude and warm regard.',
    synonyms: ['grateful', 'thankful-hearted', 'touched'],
  },
  {
    id: 'happy_appreciative_thankful',
    label: 'Thankful',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_appreciative',
    description: 'Gratitude for support, luck, or kindness.',
    synonyms: ['grateful', 'appreciative', 'fortunate'],
  },
  {
    id: 'happy_appreciative_loving',
    label: 'Loving',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_appreciative',
    description: 'Warm affection and care toward someone or something.',
    synonyms: ['affectionate', 'caring', 'fond'],
  },
  {
    id: 'happy_optimistic',
    label: 'Optimistic',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Expecting good outcomes; seeing possibility.',
    synonyms: ['upbeat', 'positive', 'forward-looking'],
  },
  {
    id: 'happy_optimistic_inspired',
    label: 'Inspired',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_optimistic',
    description: 'Energized by an idea, purpose, or vision.',
    synonyms: ['motivated', 'sparked', 'fired-up'],
  },
  {
    id: 'happy_optimistic_hopeful',
    label: 'Hopeful',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_optimistic',
    description: 'Believing improvement is possible.',
    synonyms: ['encouraged', 'expectant', 'bright-eyed'],
  },
  {
    id: 'happy_playful',
    label: 'Playful',
    level: 1,
    groupId: 'happy',
    parentId: 'happy',
    description: 'Fun, teasing, or light social energy.',
    synonyms: ['cheeky', 'fun-loving', 'breezy'],
  },
  {
    id: 'happy_playful_animated',
    label: 'Animated',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_playful',
    description: 'Lively, expressive, full of energy.',
    synonyms: ['lively', 'vivacious', 'bouncy'],
  },
  {
    id: 'happy_playful_flirty',
    label: 'Flirty',
    level: 2,
    groupId: 'happy',
    parentId: 'happy_playful',
    description: 'Playful attraction or charming social signaling.',
    synonyms: ['teasing', 'charming', 'coquettish'],
  },
];

export const happyNodes = rawHappyNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
