import type { EmotionGroup, EmotionNode } from '../types';

export const sadGroup: EmotionGroup = {
  id: 'sad',
  label: 'Sad',
  description: 'Loss, heaviness, or low-energy states.',
  color: '#2979ff',
};

const rawSadNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'sad',
    label: 'Sad',
    level: 0,
    groupId: 'sad',
    parentId: null,
    description: 'Heaviness, loss, or low energy.',
    synonyms: ['down', 'blue', 'heavy-hearted'],
  },
  {
    id: 'sad_guilty',
    label: 'Guilty',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'Feeling you did something wrong or fell short of your values.',
    synonyms: ['regretful', 'self-blaming', 'contrite'],
  },
  {
    id: 'sad_guilty_ashamed',
    label: 'Ashamed',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_guilty',
    description: 'Feeling exposed or not good enough in others’ eyes.',
    synonyms: ['embarrassed-inside', 'self-conscious', 'mortified'],
  },
  {
    id: 'sad_guilty_remorseful',
    label: 'Remorseful',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_guilty',
    description: 'Deep regret and wanting to make amends.',
    synonyms: ['regretful', 'sorry', 'penitent'],
  },
  {
    id: 'sad_abandoned',
    label: 'Abandoned',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'Feeling left alone or unsupported when you needed someone.',
    synonyms: ['left-behind', 'forsaken', 'unsupported'],
  },
  {
    id: 'sad_abandoned_ignored',
    label: 'Ignored',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_abandoned',
    description: 'Feeling unseen or not acknowledged.',
    synonyms: ['overlooked', 'dismissed', 'passed-over'],
  },
  {
    id: 'sad_abandoned_victimized',
    label: 'Victimized',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_abandoned',
    description: 'Feeling harmed or treated unfairly.',
    synonyms: ['wronged', 'mistreated', 'targeted'],
  },
  {
    id: 'sad_despair',
    label: 'Despair',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'A sense that things won’t get better.',
    synonyms: ['hopeless', 'despondent', 'defeated'],
  },
  {
    id: 'sad_despair_powerless',
    label: 'Powerless',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_despair',
    description: 'Feeling like you can’t influence what happens.',
    synonyms: ['helpless', 'stuck', 'trapped'],
  },
  {
    id: 'sad_despair_vulnerable',
    label: 'Vulnerable',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_despair',
    description: 'Feeling exposed, tender, or easily hurt.',
    synonyms: ['exposed', 'tender', 'fragile'],
  },
  {
    id: 'sad_depressed',
    label: 'Depressed',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'Low mood and low energy that can feel heavy or blank.',
    synonyms: ['downcast', 'flattened', 'drained'],
  },
  {
    id: 'sad_depressed_numb',
    label: 'Numb',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_depressed',
    description: 'Feeling emotionally muted or shut down.',
    synonyms: ['blank', 'muted', 'frozen'],
  },
  {
    id: 'sad_depressed_empty',
    label: 'Empty',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_depressed',
    description: 'Feeling hollow or lacking meaning/connection.',
    synonyms: ['hollow', 'vacant', 'void'],
  },
  {
    id: 'sad_lonely',
    label: 'Lonely',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'Wanting connection and not having it.',
    synonyms: ['alone', 'disconnected', 'isolated-inside'],
  },
  {
    id: 'sad_lonely_isolated',
    label: 'Isolated',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_lonely',
    description: 'Cut off from people or support.',
    synonyms: ['separated', 'cut-off', 'apart'],
  },
  {
    id: 'sad_lonely_unseen',
    label: 'Unseen',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_lonely',
    description: 'Feeling not recognized or not understood.',
    synonyms: ['unnoticed', 'unrecognized', 'misunderstood'],
  },
  {
    id: 'sad_bored',
    label: 'Bored',
    level: 1,
    groupId: 'sad',
    parentId: 'sad',
    description: 'Low stimulation; nothing feels engaging right now.',
    synonyms: ['uninvolved', 'under-stimulated', 'meh'],
  },
  {
    id: 'sad_bored_listless',
    label: 'Listless',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_bored',
    description: 'Low energy and motivation; dragging.',
    synonyms: ['lethargic', 'sluggish', 'drained'],
  },
  {
    id: 'sad_bored_unstimulated',
    label: 'Unstimulated',
    level: 2,
    groupId: 'sad',
    parentId: 'sad_bored',
    description: 'Not mentally engaged; needing novelty or meaning.',
    synonyms: ['unengaged', 'uninterested', 'unoccupied'],
  },
];

export const sadNodes = rawSadNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
