import type { EmotionGroup, EmotionNode } from '../types';

export const surprisedGroup: EmotionGroup = {
  id: 'surprised',
  label: 'Surprised',
  description: 'Responses to the unexpected—positive, neutral, or negative.',
  color: '#00e5ff',
};

export const rawSurprisedNodes: Omit<EmotionNode, 'colorIndex'>[] = [
  {
    id: 'surprised',
    label: 'Surprised',
    level: 0,
    groupId: 'surprised',
    parentId: null,
    description: 'A response to something unexpected.',
    synonyms: ['caught-off-guard', 'unexpected', 'taken-aback'],
  },
  {
    id: 'surprised_startled',
    label: 'Startled',
    level: 1,
    groupId: 'surprised',
    parentId: 'surprised',
    description: 'A sudden jolt of attention or alarm.',
    synonyms: ['jolted', 'spooked', 'shaken'],
  },
  {
    id: 'surprised_startled_dismayed',
    label: 'Dismayed',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_startled',
    description: 'Surprise that feels discouraging or unsettling.',
    synonyms: ['disheartened', 'crestfallen', 'alarmed'],
  },
  {
    id: 'surprised_startled_shocked',
    label: 'Shocked',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_startled',
    description: 'Strong surprise that temporarily overwhelms.',
    synonyms: ['stunned', 'speechless', 'floored'],
  },
  {
    id: 'surprised_confused',
    label: 'Confused',
    level: 1,
    groupId: 'surprised',
    parentId: 'surprised',
    description: 'Not sure what’s happening or what it means.',
    synonyms: ['puzzled', 'mixed-up', 'lost'],
  },
  {
    id: 'surprised_confused_disoriented',
    label: 'Disoriented',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_confused',
    description: 'Feeling turned around; losing your bearings.',
    synonyms: ['dazed', 'off-balance', 'turned-around'],
  },
  {
    id: 'surprised_confused_uncertain',
    label: 'Uncertain',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_confused',
    description: 'Not sure what to expect or decide.',
    synonyms: ['unsure', 'in-doubt', 'wavering'],
  },
  {
    id: 'surprised_amazed',
    label: 'Amazed',
    level: 1,
    groupId: 'surprised',
    parentId: 'surprised',
    description: 'Surprise with admiration or wonder.',
    synonyms: ['impressed', 'wow-ed', 'wonderstruck'],
  },
  {
    id: 'surprised_amazed_astonished',
    label: 'Astonished',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_amazed',
    description: 'High-intensity surprise with strong impact.',
    synonyms: ['astounded', 'staggered', 'stunned'],
  },
  {
    id: 'surprised_amazed_awestruck',
    label: 'Awestruck',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_amazed',
    description: 'Overwhelmed by wonder or greatness.',
    synonyms: ['in-awe', 'reverent', 'marveling'],
  },
  {
    id: 'surprised_excited',
    label: 'Excited',
    level: 1,
    groupId: 'surprised',
    parentId: 'surprised',
    description: 'Activated energy from something new or coming soon.',
    synonyms: ['pumped', 'amped', 'stoked'],
  },
  {
    id: 'surprised_excited_eager',
    label: 'Eager',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_excited',
    description: 'Wanting something to happen soon.',
    synonyms: ['keen', 'enthusiastic', 'ready'],
  },
  {
    id: 'surprised_excited_energetic',
    label: 'Energetic',
    level: 2,
    groupId: 'surprised',
    parentId: 'surprised_excited',
    description: 'High physical or mental energy.',
    synonyms: ['charged', 'revved', 'active'],
  },
];

export const surprisedNodes = rawSurprisedNodes.map((node, index) => ({
  ...node,
  colorIndex: index,
}));
